export const SEARCH_SUBMIT = 'SEARCH_SUBMIT';
export const LOCALE_CHANGE = 'LOCALE_CHANGE';
export const SORT_BY_CHANGE = 'SORT_BY_CHANGE';
export const SELECTED_CHANGE = 'SELECTED_CHANGE';
export const SEARCH_BY_CHANGE = 'SEARCH_BY_CHANGE';
export const SEARCH_VALUE_CHANGE = 'SEARCH_VALUE_CHANGE';
export const GET_NEXT_SEARCH_RESULTS = 'GET_NEXT_SEARCH_RESULTS';
export const GET_INITIAL_SEARCH_RESULTS = 'GET_INITIAL_SEARCH_RESULTS';
