export const SORT_CHANGE = 'SORT_CHANGE';
export const SEARCH_SUBMIT = 'SEARCH_SUBMIT';
export const SELECTED_CHANGE = 'SELECTED_CHANGE';
export const SEARCH_BY_CHANGE = 'SEARCH_BY_CHANGE';
export const SEARCH_VALUE_CHANGE = 'SEARCH_VALUE_CHANGE';
